---

  # Redhat variants
- block: # Add zerotier repo and it's gpg key
  - name: Add zerotier gpg key
    rpm_key:
      state: present
      key: https://download.zerotier.com/contact%40zerotier.com.gpg

  - name: Add zerotier repo
    yum_repository:
      name: zerotier
      description: ZeroTier, Inc. RPM Release Repository
      baseurl: https://download.zerotier.com/redhat/el/$releasever
      gpgcheck: yes
      enabled: yes
    register: zerotier_repo
  tags:
  - installation
  - repositories
  when: ansible_os_family == "RedHat"

  # Debian variants
- block: # Add zerotier repo and it's gpg key if not already done.
  - name: Check if zerotier is already installed
    package:
      name: zerotier-one
      state: present
    check_mode: true
    register: zerotier_repo

  - name: Install zerotier
    shell: curl -s 'https://pgp.mit.edu/pks/lookup?op=get&search=0x1657198823E52A61' | gpg --import && \
               if z=$(curl -s 'https://install.zerotier.com/' | gpg); then echo "$z" | sudo bash; fi
    register: zerotier_repo
    when: zerotier_repo.changed
  tags:
  - installation
  - repositories
  when: ansible_os_family == "Debian"

- block: #Install and enable zerotier-one
  - name: Install zerotier-one
    package:
      name: zerotier-one
      state: present
    register: zerotier_client

  - name: Start zerotier-one service
    service:
      name: zerotier-one
      state: started
    when:
    - zerotier_client|succeeded
    notify:
    - enable zerotier-one

  when:
  - zerotier_repo|succeeded
  - not ansible_check_mode
  tags:
  - installation
  - packages
