---
# tasks file for ansible-role-zerotier
- import_tasks: install.yml

- name: Check for successfully joined networks
  shell: zerotier-cli listnetworks | grep 'OK'| awk '{print $3}'
  register: joinednetworks

- include_tasks: join_network.yml
  when:
  - 'zerotier_network_id not in joinednetworks.stdout'
  - zerotier_accesstoken is defined
